site_name: qtstrap
site_description: 'Like Bootstrap, but Qt-er!'
site_author: 'David Kincaid'
docs_dir: docs/
repo_name: 'qtstrap/qtstrap'
repo_url: 'https://github.com/qtstrap/qtstrap'
theme:
    name: readthedocs
plugins:
  - search
  - mermaid2
  - literate-nav

nav:
    - Overview:
        - Home: index.md
        - Quickstart: 
            - Installation: quickstart/installation.md
            - Getting Started: quickstart/gettingstarted.md
            - BaseApplication: quickstart/baseapplication.md
            - BaseMainWindow: quickstart/basemainwindow.md
            - Context Layouts: quickstart/context_layouts.md
        - Project Structure: 
            - Project Structure: structure/structure.md
            - Makefile: structure/makefile.md
    - API Reference:
      - api/*